### PR TITLE
Add generated typescript definitions as part of build

### PR DESCRIPTION
**Pull request by seleb**
Adds a new script `build-types`, which generates typescript definitions for the client class (using a similar pattern to `build-rest`).

Note: this is not comprehensive. Response types are only partially defined (they aren't in the existing json schema), and the plugins are not defined, but this still greatly improves the explorability and autocomplete of the API in a TS environment.

### CODE REVIEW

**Comment by seleb** [comment]
looks like the CI is failing, but only on node < 8, and it looks like master is red as well; is the legacy node support required?

**Comment by ebisbe** [comment]
The other day I was thinking that it would be a great improvement

**Comment by ebisbe** [comment]
@jeremyruppel is there any reason to having here doing nothing instead of shipping it?

**Comment by jeremyruppel** [comment]
@ebisbe thanks for the nudge, I'm ready to get this shipped. I'll fix those TODOs in main.

**Comment by ebisbe** [comment]
I did nothing. It's all thanks to @seleb !!

**Comment by jeremyruppel** [comment]
Yes of course! Amazing work @seleb!

**Pull request merged**
