### PR TITLE
Method to get available sizes for the media item.

### PR DESCRIPTION
**Pull request by smoogly**
This depends on swagger definition here: https://github.com/flickr/flickr-api-swagger/pull/8/files

### CODE REVIEW

**Comment by jeremyruppel** [comment]
Can you bump the dependency on flickr-api-swagger to 2.7.0?

**Comment by smoogly** [comment]
@jeremyruppel, Done.
Thanks for looking at my PRs :)

**Comment by jeremyruppel** [comment]
No problem! Thank you for the contributions!

**Comment by jeremyruppel** [comment]
Published in v2.1.0

**Pull request merged**
